---
title: "EDA St. Cloud"
author: "Claude Haneum Lee, Hyesu Lee"
date: "4/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(gghighlight)
theme_set(theme_bw())
IPUMS <- read.csv("IPUMS_Cleaned.csv")
```

# Cleaning
```{r eval=FALSE, include=TRUE}
## Select Variables
IPUMS <- IPUMS0 %>% 
  select(YEAR, STATEFIP, PUMA, METAREA, HHWT, REGION, STATEFIP, COUNTYFIP, DENSITY, CITY, CITYPOP, PUMA, PERWT,
         HHTYPE, MORTAMT1, RENTGRS, HHINCOME, VALUEH, FAMSIZE, AGE, HCOVPUB,
         SCHOOL, EDUC, EDUCD, DEGFIELD, DEGFIELDD, EMPSTAT, EMPSTATD, CLASSWKR, CLASSWKRD,
         UHRSWORK, LOOKING, AVAILBLE, INCTOT, POVERTY, TRANTIME, RIDERS) %>% 
  filter(YEAR != 2011 & (
    
    # St. Cloud
    (STATEFIP == 27 & PUMA == 900) |
    # Rochester
    (STATEFIP == 27 & PUMA == 2500) |
    # Duluth
    (STATEFIP == 27 & PUMA == 500) |
    # Mankato
    (STATEFIP == 27 & PUMA == 2200) |
    # Fargo
    (STATEFIP == 38 & PUMA == 500) |
    # Grand Forks
    (STATEFIP == 38 & PUMA == 400) |
    # Eau Claire
    (STATEFIP == 55 & PUMA == 55103) |
    # La Crosse
    (STATEFIP == 55 & PUMA == 900) |
    # Dubuque
    (STATEFIP == 19 & PUMA == 700) |
    # Cedar Rapids
    (STATEFIP == 19 & PUMA == 1000)
  )) %>% 
  mutate(CITYNAME = case_when(
    (STATEFIP == 27 & PUMA == 900) ~ "St. Cloud, MN",
    (STATEFIP == 27 & PUMA == 2500) ~ "Rochester, MN",
    (STATEFIP == 27 & PUMA == 500) ~ "Duluth, MN",
    (STATEFIP == 27 & PUMA == 2200) ~ "Mankato, MN",
    (STATEFIP == 38 & PUMA == 500) ~ "Fargo, ND",
    (STATEFIP == 38 & PUMA == 400) ~ "Grand Forks, ND",
    (STATEFIP == 55 & PUMA == 55103) ~ "Eau Claire, WI",
    (STATEFIP == 55 & PUMA == 900) ~ "La Crosse, WI",
    (STATEFIP == 19 & PUMA == 700) ~ "Dubuque, IA",
    (STATEFIP == 19 & PUMA == 1000) ~ "Cedar Rapids, IA"
  ))

save(IPUMS, file = "IPUMS_Cleaned.RData")
write.csv(IPUMS, "IPUMS_Cleaned.csv")
load("IPUMS_Cleaned.Rdata")
```


# Household and Personal Income

```{r}
IPUMS_HHINCOME <- IPUMS %>% 
  filter(HHINCOME != 9999999) %>% 
  group_by(YEAR, CITYNAME) %>% 
  summarize(HHINCOME_AVG = weighted.mean(HHINCOME, HHWT, na.rm = FALSE))

ggplot(IPUMS_HHINCOME, aes(x = YEAR, y = HHINCOME_AVG, color = CITYNAME)) +
  geom_line() +
  gghighlight(CITYNAME == "St. Cloud, MN", label_key = CITYNAME, label_params = list(size = 3)) +
  labs(title = "Average Household Income", xlab = "Year") +
  scale_y_continuous(labels=scales::dollar_format()) +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.title.y = element_blank()
  )

IPUMS_PINCOME <- IPUMS %>% 
  filter(INCTOT != 9999999) %>%
  group_by(YEAR, CITYNAME) %>% 
  summarize(PINCOME_AVG = weighted.mean(INCTOT, PERWT, na.rm = FALSE))

ggplot(IPUMS_PINCOME, aes(x = YEAR, y = PINCOME_AVG, color = CITYNAME)) +
  geom_line() +
  gghighlight(CITYNAME == "St. Cloud, MN", label_key = CITYNAME, label_params = list(size = 3)) +
  labs(title = "Average Total Personal Income", xlab = "Year") +
  scale_y_continuous(labels=scales::dollar_format()) +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.title.y = element_blank()
  )
```


# Average Family Size

```{r}
IPUMS_FAMSIZE <- IPUMS %>% 
  group_by(YEAR, CITYNAME) %>% 
  summarize(FAMSIZE_AVG = weighted.mean(FAMSIZE, PERWT, na.rm = FALSE))
ggplot(IPUMS_FAMSIZE, aes(x = YEAR, y = FAMSIZE_AVG, color = CITYNAME)) +
  geom_line()  +
  gghighlight(CITYNAME == "St. Cloud, MN", label_key = CITYNAME, label_params = list(size = 3)) +
  labs(title = "Average Family Size", xlab = "Year") +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.title.y = element_blank()
  )
```


# Average First Mortgage Payment

```{r}
IPUMS_MORTAMT1 <- IPUMS %>% 
  filter(!MORTAMT1 %in% c(0, 1)) %>%
  group_by(YEAR, CITYNAME) %>% 
  summarize(MORTAMT1_AVG = weighted.mean(MORTAMT1, HHWT, na.rm = FALSE))
ggplot(IPUMS_MORTAMT1, aes(x = YEAR, y = MORTAMT1_AVG, color = CITYNAME)) +
  geom_line() +
  gghighlight(CITYNAME == "St. Cloud, MN", label_key = CITYNAME, label_params = list(size = 3)) +
  labs(title = "Average First Mortgage Payment", xlab = "Year") +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.title.y = element_blank()
  )
```


# Average Gross Rent

```{r}
IPUMS_RENTGRS <- IPUMS %>% 
  filter(HHINCOME != 0) %>% 
  group_by(YEAR, CITYNAME) %>% 
  summarize(RENTGRS_AVG = weighted.mean(RENTGRS, HHWT, na.rm = FALSE))
ggplot(IPUMS_RENTGRS, aes(x = YEAR, y = RENTGRS_AVG, color = CITYNAME)) +
  geom_line() +
  gghighlight(CITYNAME == "St. Cloud, MN", label_key = CITYNAME, label_params = list(size = 3)) +
  labs(title = "Average Gross Rent", xlab = "Year") +
  scale_y_continuous(labels=scales::dollar_format()) +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.title.y = element_blank()
  )
```


# Average Travel Time to Work

```{r}
IPUMS_TRANTIME <- IPUMS %>% 
  filter(TRANTIME != 0) %>% 
  group_by(YEAR, CITYNAME) %>% 
  summarize(TRANTIME_AVG = weighted.mean(TRANTIME, HHWT, na.rm = FALSE))
ggplot(IPUMS_TRANTIME, aes(x = YEAR, y = TRANTIME_AVG, color = CITYNAME)) +
  geom_line() +
  gghighlight(CITYNAME == "St. Cloud, MN", label_key = CITYNAME, label_params = list(size = 3)) +
  labs(title = "Average Travel Time To Work", xlab = "Year") +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.title.y = element_blank()
  )
```


# Average House Value

```{r}
IPUMS_VALUEH <- IPUMS %>% 
  filter(!VALUEH %in% c(0, 9999998, 9999999)) %>% 
  group_by(YEAR, CITYNAME) %>% 
  summarize(VALUEH_AVG = weighted.mean(VALUEH, HHWT, na.rm = FALSE))
ggplot(IPUMS_VALUEH, aes(x = YEAR, y = VALUEH_AVG, color = CITYNAME)) +
  geom_line() +
  gghighlight(CITYNAME == "St. Cloud, MN", label_key = CITYNAME, label_params = list(size = 3)) +
  labs(title = "Average House Value", xlab = "Year") +
  scale_y_continuous(labels=scales::dollar_format()) +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.title.y = element_blank()
  )
```

